// ══════════════════════════════════════════════════════════════════════════
// EXPORTS
// ══════════════════════════════════════════════════════════════════════════

function exportGapCSV() {
  const g = state.gapResults;
  if (!g) { toast('Run gap analysis first', 'warning'); return; }
  const rows = [['Doc Topic','Path','Coverage','Score %','Best Match','Module URL','Author','ms.date'].join(',')];
  for (const r of g.results) {
    rows.push([
      `"${(r.docTopic.title||'').replace(/"/g,'""')}"`,
      `"${(r.docTopic.path||'').replace(/"/g,'""')}"`,
      r.coverage,
      Math.round(r.score * 100),
      r.bestMatch ? `"${r.bestMatch.title.replace(/"/g,'""')}"` : '',
      r.bestMatch ? r.bestMatch.learnUrl : '',
      r.bestMatch ? r.bestMatch.author : '',
      r.bestMatch ? r.bestMatch.msDate : '',
    ].join(','));
  }
  const blob = new Blob([rows.join('\n')], { type: 'text/csv' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `gap-analysis-${(state.selectedProduct?.name||'product').replace(/\s+/g,'-').toLowerCase()}-${new Date().toISOString().slice(0,10)}.csv`;
  a.click();
  toast('CSV exported', 'success');
}

function exportGapHTML() {
  const g = state.gapResults;
  if (!g) { toast('Run gap analysis first', 'warning'); return; }
  const name = state.selectedProduct?.name || 'Product';
  const uncovered = g.results.filter(r => r.coverage === 'uncovered');
  const partial = g.results.filter(r => r.coverage === 'partial');
  const covered = g.results.filter(r => r.coverage === 'covered');

  const html = `<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>Gap Analysis Report — ${escHtml(name)}</title>
<link rel="stylesheet" href="css/styles.css" /></head><body>
<h1>📊 Gap Analysis Report — ${escHtml(name)}</h1>
<p>Generated ${new Date().toLocaleString()} · ${g.total} doc topics analyzed against ${state.modules.length} training modules<br>Source: ${state.selectedProduct?.repo || ''}</p>
<div class="stats">
  <div class="stat"><div class="stat-val">${g.coveragePct}%</div><div class="stat-label">Coverage</div></div>
  <div class="stat"><div class="stat-val" style="color:#107c10;">${g.covered}</div><div class="stat-label">Covered</div></div>
  <div class="stat"><div class="stat-val" style="color:#f59e0b;">${g.partial}</div><div class="stat-label">Partial</div></div>
  <div class="stat"><div class="stat-val" style="color:#a4262c;">${g.uncovered}</div><div class="stat-label">Uncovered</div></div>
</div>
<div class="bar">
  <div class="g" style="width:${(g.covered/g.total*100).toFixed(1)}%;"></div>
  <div class="y" style="width:${(g.partial/g.total*100).toFixed(1)}%;"></div>
  <div class="r" style="width:${(g.uncovered/g.total*100).toFixed(1)}%;"></div>
</div>
<h2>🚨 Not Covered (${uncovered.length})</h2>
<table><tr><th>Documentation Topic</th><th>Path</th></tr>
${uncovered.map(r => `<tr><td>${escHtml(r.docTopic.title)}</td><td style="font-size:11px;color:#666;">${escHtml(r.docTopic.path)}</td></tr>`).join('')}
</table>
<h2>⚠️ Partially Covered (${partial.length})</h2>
<table><tr><th>Documentation Topic</th><th>Closest Training</th><th>Score</th></tr>
${partial.map(r => `<tr><td>${escHtml(r.docTopic.title)}</td><td>${escHtml(r.bestMatch?.title||'—')}</td><td>${Math.round(r.score*100)}%</td></tr>`).join('')}
</table>
<h2>✅ Covered (${covered.length})</h2>
<table><tr><th>Documentation Topic</th><th>Training Match</th><th>Score</th></tr>
${covered.map(r => `<tr><td>${escHtml(r.docTopic.title)}</td><td>${escHtml(r.bestMatch?.title||'—')}</td><td>${Math.round(r.score*100)}%</td></tr>`).join('')}
</table>
<div class="footer">Generated by Team Content Gap Manager — BizApps &amp; Dynamics</div>
</body></html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `gap-report-${(name).replace(/\s+/g,'-').toLowerCase()}-${new Date().toISOString().slice(0,10)}.html`;
  a.click();
  toast('HTML report exported', 'success');
}
